### ISSUE TITLE
Git関係コマンド

### ISSUE THREAD

**Issue by awakia** [HiroNonoyama/training#2]
## Git
- [x] add (-p)
- [x] reset
- [x] checkout (-b)
- [x] commit (-m)
- [x] status
- [x] diff (--cached)
- [x] push
- [x] pull
- [x] clone
- [x] log
- [x] merge
- [x] rebase
- [x] 上のコマンドを、「masterの状態を最新にして、自分でコードを変更して、pull requestを出してマージされるまで」 で使う順に並べストーリーを語る。(使わないのもあるけど、出来る限りシチュエーションを考えて全て使おうとするうこと)
- [x] http://qiita.com/awakia/items/4c599ebe29a8b2b6ca27 のgitの設定を読んで各コマンドの意味を理解
- [x] https://github.com/wantedly/wantedly/network の意味を理解
  - [x] 例えば、一番最後にmasterにマージされたコードは誰のコードか
  - [x] 次に入りそうな大きめの機能はどれか

**Comment by HiroNonoyama** [comment]
(git clone http://github.com/wantedly/wantedly)

git log
(origin/masterに変更がある)
git pull origin master
git checkout -b issue1
(issue1に変更を加える)
git add file1
(issue1に再度変更を加える)
git status
git reset
git add file2
git status
git diff --cached
git commit -m "file2 changed"
git push origin issue1

pullrequest送る
(git merge issue1)

まずcloneして少し時間がたった状態で、コミットlogを確認したところ変更点があったので、
ローカルのmasterブランチに反映させるためにpullをする。
それからissue1という名前でブランチを切る。
file1に変更を加えたので、indexにaddする。
その後file2にも変更を加えたためcommitしようとするが、その前にindexを確認したところ、file1の変更が存在したが、
よくよく考えると誤った変更だったためindexをresetする。
それからやっとfile2をindexにaddする。
commitをする前にdiff--cachedで確認したらfile2のみの変更が正しく示されたので、
そのままcommitした。
リモートのissue1へpushし、

PullRequestを出す。
(issue1をmergeしてもらう。)

amend => どのディレクトリからでもHEADブランチへ変更をコミットする
logg => 変更したファイルを色分けして表示
mergelog => mergeしたコミットを色分けして表示
history => 歴史をわかりやすく表示かつ日付を2000-01-01の形で色分け表示
unmerged => これはわかりませんでした。
sync => masterブランチへ移動し、origin/masterの変更を取り込む。リモートブランチから削除されたブランチをローカルからも削除し、mergeされていないコミットを含むブランチを強制的に消す。また、masterに含まれないかつ"*"を含まないかつマージ済みのブランチを削除する。

最後にmasterへマージされたコード => @KentoMoriwaki
次に入りそうな大きめの機能 => Facebookページヘの投稿機能(∵累積のcommit数も多いし、最後の方にtestとかspecに関するcommitメッセージがあるからという感覚的な判断です。)

**Comment by awakia** [comment]
`git unmerged`は`git --no-pager diff --name-only --diff-filter=U`ということは分かっているんだよね？
何でこのコマンドの意味がわからないんだろう？

**Comment by HiroNonoyama** [comment]
ググり力が足りなくてずっと「--no-pager」と検索していたのでいつまでたっても見つかりませんでした。「no pager」と検索したところ見つかりました。っていうのと実際にコマンドラインで打って比較してみればよかったです。
git --no-pager diff --name-only --diff-filter=U は
今調べたところ、--no-pagerは折りたたみ無しで全部表示するので、--name-onlyはファイル名のみの表示で、--diff-filter=Uはマージしていないファイルなので、マージしていないファイル名を表示するコマンドでした。よろしくお願いします！

**Comment by HiroNonoyama** [comment]
お疲れ様です。夜遅くに失礼致します。
先週gitの設定に関する解答をさせて頂きました。もしかしたらこのissueの存在が忘れ去られてしまったのではないかと思い、コメントをさせて頂きました。
新しいインターンの方もたくさん入り、お忙しいとは思いますが、お時間作って頂ける際に次の課題を頂けると幸いです。やる気だけはありますので、ぜひよろしくお願い致します。

**Comment by awakia** [comment]
リマインド偉い。

次はGithubね。
